### ISSUE TITLE
Please ensure the DOM element exists before rendering a template into it

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ciscoheat/mithril-hx#12]
I get the error

```
Please ensure the DOM element exists before rendering a template into it
```

When running a very simple example. Do I need to take some action to create the DOM element?

**Comment by ciscoheat** [comment]
Maybe it's too simple. :) Sounds like a DOM loading event problem. Can you post your code so I can take a look? Also, did you try the example here? https://github.com/ciscoheat/mithril-hx#from-scratch

**Comment by RudolfVonKrugstein** [comment]
Interestingly I just tried the same example at work and it did work, no Problem. I will try again at home and report :-). Closing it for now.

**Comment by RudolfVonKrugstein** [comment]
Ok, I do not get it to work at my home-laptop. My example has the following files:

Main.hx
```
package ;

import mithril.M;
import js.Browser;

class Main {
  static public function main() {
    M.mount(Browser.document.body, new components.CreateTables());
  }
}
```

CreateTables.hx
```
package components;

import mithril.M;

class CreateTables implements Component {
  public function new() {}
  public function controller() {}
  
  public function view() {
    H1("Create Tables",
      BUTTON("Submit")
    );
  }
}
```

index.html
```
<!doctype html>
<title>Prompt Admin</title>
<script src="http://cdnjs.cloudflare.com/ajax/libs/mithril/0.2.0/mithril.min.js"></script>
<script src="admin.js"></script>
```

compile.hxml
```
-main Main
-cp src
-lib mithril
-js build/admin.js
```

It works at my work computer (using chromium, ubuntu64) but gives the error

```
Please ensure the DOM element exists before rendering a template into it
```

On my home-laptop (also chromium, ubuntu64).

So strange ...

**Comment by RudolfVonKrugstein** [comment]
Oh, but the example on the page works on both computers!

**Comment by ciscoheat** [comment]
Ah yes, I've seen the same thing and mentioned it to @lhorie, but it was a long time ago. It doesn't work for me either if the `<body>` element is missing. According to the Mithril [getting started page](http://mithril.js.org/getting-started.html) it should, but I've had the same problem so I added the body element on the Haxe example page. It would be interesting to know why it works on some browsers though.

**Comment by RudolfVonKrugstein** [comment]
Ah, ok, that was it. Thanks!
Well, the strangest thing is that my work and home computer are setup identically. Same OS, same OS version, same browser.
