### ISSUE TITLE
Problems with @prop

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ciscoheat/mithril-hx#14]
Trying to follow the tutorial, I created a model class like this:

```
package models;

import mithril.M;

class AuthData {

  // Authentication data
  @prop public var username : String;
  @prop public var password : String;

  public function new() {
    this.username = M.prop("");
    this.password = M.prop("");
  }
}
```

But I get this compile error:

```
Error:(12, 4) mithril.GetterSetter<String> should be String
```

Mmh, am I using @prop not correctly?

**Comment by ciscoheat** [comment]
The class you're using must implement one of the Mithril interfaces, in this case `Model` or just `Mithril` will work. Read more about it here: https://github.com/ciscoheat/mithril-hx#implement-one-of-the-following-interfaces

Btw, make sure you're using the latest version (0.25.2 as of now), I did some prop modifications that might have been broken in 0.25.1.

**Comment by RudolfVonKrugstein** [comment]
thx
