### ISSUE TITLE
Multiple properties in sugaertags

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ciscoheat/mithril-hx#15]
Can I have multiple properties in sugertags syntax? How would I list them?

Something like this ...?
```
INPUT[type=password;name=password]()
```

**Comment by ciscoheat** [comment]
No problem, just add them in separate brackets:

```haxe
INPUT[type=password][name=password]()
```

If the value is non-alphanumeric, you can use a string instead.

```haxe
A[href="/some%20strange/url"]()
```

**Comment by RudolfVonKrugstein** [comment]
thx
