### ISSUE TITLE
Putting together a table from functions or components

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ciscoheat/mithril-hx#19]
I am trying to do something like this:

```
TABLE([
  TR(),
  calcRows(1),
  calcRows(2),
  TR(),
])
```

Where calcRows outputs several table rows (so its output is an array).
```
function calcRows() {
  return [TR(),TR()];
}
```
To get this work I tried:

```
TABLE(
  [TR()].concat(
  calcRows(1)).concat(
  calcRows(2)).concat(
  [TR()]
)
```

Which gives a type error. I do not know which type "calcRows" should return.

Can this be done? Maybe using components? This compiles:

```
TABLE(
  [TR()].concat(
  M.component(calcComp1)).concat(
  M.component(calcComp2)).concat(
  [TR()]
)
```

Here the calcComp1/calcComp2 view function are identically to calcRows.

But executing this, I get the error:

```
Component template must return a virtual element, not an Array, String, e.t.c.
```

Thanks!

**Comment by ciscoheat** [comment]
Try the latest version of the mithril library on haxelib, it will make `view()` return `Dynamic` if you don't specify a return value, so your first example should work. It did for me.
