### ISSUE TITLE
@prop not working with haxe dev version (3.3.0)

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ciscoheat/mithril-hx#20]
I get errors telling me that the variable is regognized as a variable, not as a function. So I get an error like this:

```
Error:(109, 53) String cannot be called
```

**Comment by ciscoheat** [comment]
Ok thanks, I haven't tested 3.3 but it's good to know.

**Comment by ciscoheat** [comment]
Hi, do you still have this problem? I've been using prop in 3.3 for a while now and it seems to work fine.

**Comment by RudolfVonKrugstein** [comment]
I am not using it anymore, so I do not know.

**Comment by ciscoheat** [comment]
Ok, closing this then. Thanks!
