### ISSUE TITLE
Mithril __init__ code, causes problems if included twice

### ISSUE THREAD

**Issue by benmerckx** [ciscoheat/mithril-hx#21]
If you compile and use two scripts, using the mithril externs, in the same page the __init__ code runs twice, which causes an infinite loop in m.mount. Could you provide a way to not include the __init__ code using a define for example, or maybe even better check if the initialization has already run so it doesn't run twice?

**Comment by ciscoheat** [comment]
Good point, please update haxelib now, this has been fixed in the latest version. Let me know if the problem persists!
