### ISSUE TITLE
Unknown identifier : M

### ISSUE THREAD

**Issue by benmerckx** [ciscoheat/mithril-hx#22]
Hey, since commit 740cddf I have been noticing the following error:
`ModuleBuilder.hx:215: characters 8-9 : Unknown identifier : M`

This only happens if you import one of the interfaces that use "injectCurrentModule" directly like so:
`import mithril.M.Component;`
In this case M is not defined, only Component. 
This can be easily fixed by changing 
`if(M.__haxecomponents.length && untyped !this.controller) {`
to include the package like so:
`if(mithril.M.__haxecomponents.length && untyped !this.controller) {`

**Comment by ciscoheat** [comment]
Thanks, I'll fix that! I'll let you know when I've updated Haxelib.

**Comment by ciscoheat** [comment]
Updated now, let me know if it still doesn't work.

**Comment by benmerckx** [comment]
Thanks! Update works.
