### ISSUE TITLE
Error when using mithril 0.27.0

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ciscoheat/mithril-hx#24]
Hey,

I just upgraded von mithril 0.25.6, now I get this error in my program:

```
Uncaught ReferenceError: $hxClasses is not defined
```

I am using haxe 3.2.1

**Comment by RudolfVonKrugstein** [comment]
Happens with the example from the README.md too

**Comment by RudolfVonKrugstein** [comment]
This commit: 0a2334ea696f7c8ed78565265bfa0651b6fe5ec4 does not fix it for me

**Comment by ciscoheat** [comment]
Ok, using try/catch instead, so it should be fixed now in 0.27.2.

**Comment by RudolfVonKrugstein** [comment]
oh, wow, that was fast. I thought I was mistaken, and it suddenly worked. Byt you already commit the fix :-).
It works now! Thanks!

**Comment by ciscoheat** [comment]
No problem :)
