### ISSUE TITLE
CS Serverrendering: namespace error (T4, T3)

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/mithril-hx#26]
Hi Andreas!

When compiling a server renderer example for cs, the Haxe compilation works fine, but the C# compiler complains as follows:

```
src\mithril\M.cs(170,93): error CS0246: Det gick inte att hitta typ- eller namnområdesnamnet T4 (saknas ett using-direktiv eller en sammansättningsreferens?)
src\mithril\M.cs(170,100): error CS0246: Det gick inte att hitta typ- eller namnområdesnamnet T3 (saknas ett using-direktiv eller en sammansättningsreferens?)
```

(Sorry for swedish compilation messages - should be no problem for you, I guess :-)

Any idea? (Doesn't seem to be a dce thing - no difference with -dce no. Btw, I don't know if cs cares about dce at all...)

No hurry on this issue - no breaks in production for me because of this..!

Best! / Jonas

**Comment by ciscoheat** [comment]
Hello :) Can you attach the file `M.cs` here so I can take a look? I suspect some deeper issue, but just to be sure.

**Comment by cambiata** [comment]
Sure! Here it is!
[M.cs.txt](https://github.com/ciscoheat/mithril-hx/files/463365/M.cs.txt)

**Comment by cambiata** [comment]
Seems to be the same problem on java:
```
src/mithril/M.java:50: error: cannot find symbol
				haxe.lang.Function __temp_odecl1 = new mithril.M_deferred_283__Fun<T2, T4, T, T3>();
				                                                                       ^
  symbol:   class T4
  location: class M
src/mithril/M.java:50: error: cannot find symbol
				haxe.lang.Function __temp_odecl1 = new mithril.M_deferred_283__Fun<T2, T4, T, T3>();
				                                                                              ^
  symbol:   class T3
  location: class M
2 errors
```

**Comment by ciscoheat** [comment]
@waneck do you have any idea what could be the problem here?

**Comment by cambiata** [comment]
Closing this issue - 1.0 works fine with C# target, it seems.
