### ISSUE TITLE
Wiki bug - MVC

### ISSUE THREAD

**Issue by staypufd** [ciscoheat/mithril-hx#28]
The GOF patterns did not come till the 90's. Specifically 1992. It was released at OOPSLA '92. It took approx 2 years before they took hold in a massive way.

**Comment by ciscoheat** [comment]
Hi, thanks for noticing, but I'm referring to especially to 

> software design patterns, later known as the "GoF patterns".

Software design patterns has been in the works during the 80:s, Beck and Cunningham presented some initial results at OOPSLA in 1987.
