### ISSUE TITLE
Does / will this work with mithril@rewrite (1.0)?

### ISSUE THREAD

**Issue by IBwWG** [ciscoheat/mithril-hx#29]
If so, is there anything special needed to do so?

**Comment by ciscoheat** [comment]
This library will also require a rewrite, but I'm working on it! What I have so far is promising, and soon I'll push a rewrite branch which will be compatible with mithril 1.0.

**Comment by ciscoheat** [comment]
Good news, I have made all the examples working with Mithril 1.0, so this library will compatible. The only difference will be the `this` reference in lifecycle methods, and view (in other words, all methods taking a `vnode` as argument). In mithril it will refer to `vnode.state`, but in Haxe it will refer to `vnode.tag`, which is the instantiated Haxe object.
