### ISSUE TITLE
When running under the latest node, `GLOBAL` is deprecated in favour of `global`

### ISSUE THREAD

**Issue by hamaluik** [ciscoheat/mithril-hx#31]
When running under the latest node, I get:

```
[DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
```

Which can be fixed by replacing `GLOBAL` on lines https://github.com/ciscoheat/mithril-hx/blob/master/src/mithril/M.hx#L165-L166 with `global`.

**Comment by ciscoheat** [comment]
Thank you! A new haxelib version has been released.
