### ISSUE TITLE
Works with Mithril 2?

### ISSUE THREAD

**Issue by fullofcaffeine** [ciscoheat/mithril-hx#32]
Hi Andreas!

I'm about to start a new js project and would like to use Mithril and Mithrilhx. Is Mithril 2+ is supported by your lib?

Cheers!

**Comment by ciscoheat** [comment]
Now that Mithril 2.0 is released, I'm working on supporting it. Seems pretty good so far.

**Comment by ciscoheat** [comment]
The release has just been made, keeping this open for a while in case you find something, @fullofcaffeine.

**Comment by shyaml** [comment]
i'm getting this error 
example/webshop/ShoppingCart.hx:93: characters 15-17 : Unexpected ->

when i ran the webshop example
