### ISSUE TITLE
Vnode state is no longer typed?

### ISSUE THREAD

**Issue by hamaluik** [ciscoheat/mithril-hx#34]
Here https://github.com/ciscoheat/mithril-hx/commit/6739d34445fd063ff04362665c31f5f62d0b2b3a#diff-325ff780c8b003fccb2a4abb89c532a9R55-R56 you removed the generic on Vnode and turned it into a `Dynamic` for the vnode state. This removes static analysis and code completion, and it doesn't seem to have gained anything? Unless I'm missing something, can we bring the generic back?

**Comment by ciscoheat** [comment]
Hi, thanks for your feedback! Since I always used the Haxe-class based style of using Mithril, where the state is in the classes, I saw no need for the generic. But as you say, it does no harm so I'll restore it for version 2.1.

**Comment by hamaluik** [comment]
Awesome, thanks!

**Comment by ciscoheat** [comment]
It's back now, can you review if it's ok for you to use?

**Comment by hamaluik** [comment]
Will do when I have a chance, might be a couple days. Thanks!

**Comment by hamaluik** [comment]
Works great, thanks!

**Comment by ciscoheat** [comment]
Perfect, thanks for checking!
