### ISSUE TITLE
noderendering dependency missing

### ISSUE THREAD

**Issue by axelhuizinga** [ciscoheat/mithril-hx#5]
just tried to run the noderendering example and got:
 node noderendering.js "server"

/var.../noderendering.js:172
        this.ip = Mithril.prop(""); //DashboardModule.hx:24
ReferenceError: Mithril is not defined

also inside of the NodeRendering class there are two calls to
 require("mithril-node-render");

I don't have any idea how this will work.

**Comment by ciscoheat** [comment]
This was just tested and working with Mithril 0.1.30 and haxelib version 0.19.1 of this library, so I'm closing this issue for now.
